### ISSUE TITLE
Strip action spawns HUD helmet object and not HUD helmet (spare) object.

### ISSUE THREAD

**Issue by AluminumAlman** [dastrukar/hideous-helmet#1]
The helmet strip actions removes the player's helmet, however, it doesn't spawn the HUD helmet (spare) object, but a HUD helmet. This issue makes it so that the helmet uses a garrison armor texture while in backpack and removing it from the backpack duplicates it.
It's easy to reproduce the bug: start the game with the loadout `hdh, bak`, wear the spare helmet, strip off the helmet (the helmet should be on the ground), hold your backpack and grab the helmet off the ground and into the backpack. The helmet inside the backpack should have the texture of garrison armor. Removing it from the backpack causes two HUD helmet objects to spawn.

**Comment by dastrukar** [comment]
Huh, that's odd. Seems like you don't even need to strip off the helmet to dupe it.
It appears that using `summon hhelmet` will also spawn 2 helmets.

Will try to fix it soon. Thanks for letting me know!

**Comment by dastrukar** [comment]
Should be fixed with commit 73e7b504ff00067311851d02f92b9266d5649dea
