### ISSUE TITLE
Updated Compatibility

### ISSUE THREAD

**Issue by VBawss** [dastrukar/hideous-helmet#2]
There are currently some HUD issues which I've noticed while doing a recent playthru that I thought should be addressed. These occur when you're not wearing a helmet and Hide Weapon Status is set to Yes.
- Pistol always displays single shot mode even if the weapon isn't capable of changing firemodes i.e. a standard pistol
- SMG doesn't display full auto. It's literally just a blank space where STFULAUT should be
- Thunder Buster doesn't display spray mode. Same as above. Just a blank space where STBURAUT should be
- Hunter doesn't display full auto. 
- [Nyx](https://gitlab.com/icarus-innovations/hdest-addons/nyx) doesn't display burst fire.
- [Bitch](https://gitlab.com/icarus-innovations/hdest-addons/bitch) doesn't display any firemodes. It is capable of semi, burst and full auto and displays none of these.
- [Fenris](https://gitlab.com/icarus-innovations/hdest-addons/fenris) doesn't display single shot. Fenris was overhauled fairly recently and has semi and full auto fire modes.
- Needs compatibility with [HEV Armor](https://gitlab.com/icarus-innovations/hdest-addons/hev-armor). Armor durability is displayed regardless of if a helmet is worn or not.

**Comment by dastrukar** [comment]
> * SMG doesn't display full auto. It's literally just a blank space where STFULAUT should be
> * Thunder Buster doesn't display spray mode. Same as above. Just a blank space where STBURAUT should be
> * Hunter doesn't display full auto.
> * Nyx doesn't display burst fire.

That's odd. These seem to work fine for me...

**Comment by dastrukar** [comment]
Added support for The Bitch and HEV Armor (patch is in [hh_patches](https://github.com/dastrukar/hideous-helmet/tree/master/hh_patches)), fixed the Fenris's firemode not displaying properly, and the pistol should no longer display the firemode when incapable of switching modes.

Also, just curious, does the "firemode not displaying" problem occur when only using Hideous Helmet?

**Comment by VBawss** [comment]
Just updated and tested to confirm and yes, this still occurs even when using only HD and Hideous Helmet. New issue that I just discovered after updating is that the firemode doesn't display on the double barrel either. Not really a big deal if I'm being honest mostly because you have to hold the firemode button down to fire both barrels so there's never any doubt in the users mind about what firing mode is being used. Here's a video I recorded [a short video](https://streamable.com/c2i66h) showing exactly what's on my screen. This is after updating just now and the only mods being loaded besides HD and Hideous Helmet are HEV Armor, Nyx and Fenris.

**Comment by dastrukar** [comment]
Okay, I still can't replicate the firemode problem. For me, it shows up just fine:

![hdest-weaponfiremodes](https://user-images.githubusercontent.com/32709291/143902512-d5b23095-130f-46b5-b5a5-9403e826f3dc.png)
*(using latest HDest main, Nyx, and Fenris)*

Is it possible for me to get a copy of your mod files?

As for the HEV Armor, you have to load the folder named `hev-armor` located in `hh_patches`. (sorry for the inconvenience)

(sorry to go off topic but, is it intentional that the HEV Armor doesn't stun you when you take it off?)

**Comment by VBawss** [comment]
Fixed with latest commit. Thank you.
