### ISSUE TITLE
4.10.0b Version?

### ISSUE THREAD

**Issue by JCGemX** [dastrukar/hideous-helmet#6]
Your read me says to use the release version that matches HDest's version, but there isn't one for the latest build.

Are there any plans for one in the future?

(Doesn't have to be in the _near_ future, I just want to know if it will happen at all)

(Also thank you for basically integrating "Debug Counters" into this, I can't wait to use this)

**Comment by dastrukar** [comment]
To be honest, I kind of forgot to add one for v4.10.0b, will do it later.
Just download the hudcore branch, it should work fine with the latest release afaik.

**Comment by dastrukar** [comment]
Also, unrelated but, if you want a more debug hud experience, you should check out Undead Zeratul's mod https://github.com/UndeadZeratul/hideous-helmet-extended

**Comment by JCGemX** [comment]
(Woah, I wasn't expecting a response this quickly)

I can't, it spits a bunch of errors at me:

hideous-helmet-hudcore.pk3:zscript/armour/hharmouroverride_hdarmourworn.zs, line 1: Class HHArmourOverride_HDArmourWorn has unknown base class HCItemOverride
hideous-helmet-hudcore.pk3:zscript/helmet/hhhelmetoverride.zs, line 4: Class HHHelmetOverride has unknown base class HCItemOverride
hideous-helmet-hudcore.pk3:zscript/armour/hharmouroverride_hdarmourworn.zs, line 3: Attempt to override non-existent virtual function Init
hideous-helmet-hudcore.pk3:zscript/armour/hharmouroverride_hdarmourworn.zs, line 9: Attempt to override non-existent virtual function checkitem
hideous-helmet-hudcore.pk3:zscript/armour/hharmouroverride_hdarmourworn.zs, line 14: Attempt to override non-existent virtual function DrawHUDStuff
hideous-helmet-hudcore.pk3:zscript/helmet/hhhelmetoverride.zs, line 6: Attempt to override non-existent virtual function Init
hideous-helmet-hudcore.pk3:zscript/helmet/hhhelmetoverride.zs, line 12: Attempt to override non-existent virtual function checkitem

**Comment by dastrukar** [comment]
Are you loading HUDCore? Also, make sure that you're using the latest master of HUDCore.

**Comment by JCGemX** [comment]
Okay, I found the problem, I was using the 4.10.0a version of HUDCore, and I thought it was 4.10.0b.

**Comment by dastrukar** [comment]
Made a v4.10.0b release. Also did the same for HUDCore.
